import { Question, UserProfile, UserRole } from './types';

export const ADMIN_KEY = "bS%83B4+4uAO-#&&UyK;H+";

export const USERS: UserProfile[] = [
  { id: 'u1', name: 'Mahmoud', pin: '77337733w', role: UserRole.USER },
  { id: 'u2', name: 'Ismail', pin: '77002887p', role: UserRole.USER },
  { id: 'u3', name: 'Ayoub', pin: '00229900e', role: UserRole.USER },
];

// Helper to generate IDs
let qId = 1;

const createQ = (en: string, fr: string, ar: string, section: string, isPuzzle = false): Question => ({
  id: qId++,
  section,
  text: { en, fr, ar },
  isPuzzle
});

const createPuzzle = (en: string): Question => ({
  id: qId++,
  section: 'Logic & Reasoning',
  text: { en, fr: en + " (Traduction non requise pour l'énigme)", ar: en + " (الترجمة غير مطلوبة للغز)" }, // Puzzles are universal per instructions, shown in EN usually or translated if critical, but prompt implies universal logic. We will map EN text to others for display consistency.
  isPuzzle: true
});

export const QUESTIONS: Question[] = [
  // SECTION 1: PERSONALITY & MINDSET
  createQ("How do you describe yourself in a team?", "Comment te décris-tu dans une équipe ?", "كيف تصف نفسك داخل فريق؟", "Mindset"),
  createQ("What stresses you the most at work?", "Qu’est-ce qui te stresse le plus au travail ?", "ما أكثر شيء يضغط عليك في العمل؟", "Mindset"),
  createQ("How do you stay productive under pressure?", "Comment restes-tu productif sous pression ?", "كيف تبقى منتجًا تحت الضغط؟", "Mindset"),
  createQ("Do you prefer working alone or in a team? Why?", "Préfères-tu travailler seul ou en équipe ? Pourquoi ?", "هل تفضل العمل وحدك أم مع فريق؟ ولماذا؟", "Mindset"),
  createQ("What does failure mean to you?", "Que signifie l’échec pour toi ?", "ماذا يعني الفشل بالنسبة لك؟", "Mindset"),
  createQ("Describe a failure you learned from.", "Décris un échec dont tu as appris.", "صف فشلًا تعلمت منه.", "Mindset"),
  createQ("What motivates you the most?", "Qu’est-ce qui te motive le plus ?", "ما الذي يحفزك أكثر؟", "Mindset"),
  createQ("How do you deal with difficult people?", "Comment gères-tu les personnes difficiles ?", "كيف تتعامل مع الأشخاص الصعبين؟", "Mindset"),
  createQ("Money or growth — which matters more to you?", "Argent ou évolution — lequel compte le plus ?", "المال أم التطور — أيهما أهم بالنسبة لك؟", "Mindset"),
  createQ("How do you react to criticism?", "Comment réagis-tu aux critiques ?", "كيف تتعامل مع النقد؟", "Mindset"),
  createQ("What is your biggest strength?", "Quelle est ta plus grande force ?", "ما أكبر نقطة قوة لديك؟", "Mindset"),
  createQ("What is your biggest weakness?", "Quelle est ta plus grande faiblesse ?", "ما أكبر نقطة ضعف لديك؟", "Mindset"),
  createQ("How do you organize your time?", "Comment organises-tu ton temps ?", "كيف تنظم وقتك؟", "Mindset"),
  createQ("What does leadership mean to you?", "Que signifie le leadership pour toi ?", "ماذا تعني القيادة بالنسبة لك؟", "Mindset"),
  createQ("Do you ask for help when needed?", "Demandes-tu de l’aide quand il le faut ?", "هل تطلب المساعدة عند الحاجة؟", "Mindset"),
  createQ("Where do you see yourself in 3 years?", "Où te vois-tu dans 3 ans ?", "أين ترى نفسك بعد 3 سنوات؟", "Mindset"),
  createQ("What makes you lose focus?", "Qu’est-ce qui te fait perdre la concentration ?", "ما الذي يجعلك تفقد التركيز؟", "Mindset"),
  createQ("How do you react when you make a mistake?", "Comment réagis-tu quand tu fais une erreur ?", "كيف تتصرف عندما ترتكب خطأ؟", "Mindset"),
  createQ("What does success mean to you?", "Que signifie le succès pour toi ?", "ماذا يعني النجاح بالنسبة لك؟", "Mindset"),
  createQ("Why should we trust you?", "Pourquoi devrions-nous te faire confiance ?", "لماذا يجب أن نثق بك؟", "Mindset"),

  // SECTION 2: WORK & SKILLS
  createQ("What skills do you use the most?", "Quelles compétences utilises-tu le plus ?", "ما المهارات التي تستخدمها أكثر؟", "Skills"),
  createQ("What did you learn recently?", "Qu’as-tu appris récemment ?", "ماذا تعلمت مؤخرًا؟", "Skills"),
  createQ("How do you improve yourself professionally?", "Comment t’améliores-tu professionnellement ?", "كيف تطور نفسك مهنيًا؟", "Skills"),
  createQ("Which tool can you not work without?", "Quel outil est indispensable pour toi ?", "ما الأداة التي لا يمكنك العمل بدونها؟", "Skills"),
  createQ("How do you solve a problem you never faced before?", "Comment résous-tu un problème inconnu ?", "كيف تحل مشكلة لم تواجهها من قبل؟", "Skills"),
  createQ("Describe a project you are proud of.", "Décris un projet dont tu es fier.", "صف مشروعًا تفخر به.", "Skills"),
  createQ("How do you handle deadlines?", "Comment gères-tu les délais ?", "كيف تتعامل مع المواعيد النهائية؟", "Skills"),
  createQ("How do you split a big task?", "Comment divises-tu une grande tâche ?", "كيف تقسم مهمة كبيرة؟", "Skills"),
  createQ("What is quality work for you?", "Qu’est-ce qu’un travail de qualité pour toi ?", "ما هو العمل الجيد بالنسبة لك؟", "Skills"),
  createQ("Do you work the same without supervision?", "Travailles-tu pareil sans supervision ?", "هل تعمل بنفس المستوى دون مراقبة؟", "Skills"),
  createQ("How do you handle errors?", "Comment gères-tu les erreurs ?", "كيف تتعامل مع الأخطاء؟", "Skills"),
  createQ("What role suits you best in a team?", "Quel rôle te convient le mieux ?", "ما الدور الأنسب لك في الفريق؟", "Skills"),
  createQ("How do you review your work?", "Comment vérifies-tu ton travail ?", "كيف تراجع عملك؟", "Skills"),
  createQ("What skill do you need to improve now?", "Quelle compétence dois-tu améliorer maintenant ?", "ما المهارة التي تحتاج لتطويرها الآن؟", "Skills"),
  createQ("What does responsibility mean to you?", "Que signifie la responsabilité pour toi ?", "ماذا تعني المسؤولية بالنسبة لك؟", "Skills"),
  createQ("How do you manage multitasking?", "Comment gères-tu le multitâche ?", "كيف تتعامل مع تعدد المهام؟", "Skills"),
  createQ("What is your workflow?", "Quel est ton workflow ?", "ما هو أسلوب عملك؟", "Skills"),
  createQ("How do you measure task success?", "Comment mesures-tu le succès d’une tâche ?", "كيف تقيس نجاح المهمة؟", "Skills"),
  createQ("What makes you stop working?", "Qu’est-ce qui te fait arrêter de travailler ?", "ما الذي يجعلك تتوقف عن العمل؟", "Skills"),
  createQ("Do you ask for feedback? Why?", "Demandes-tu des retours ? Pourquoi ?", "هل تطلب ملاحظات؟ ولماذا؟", "Skills"),

  // SECTION 3: THINKING & VALUES (Expanded to reach 100 total Qs)
  createQ("What is intelligence to you?", "Qu'est-ce que l'intelligence pour toi ?", "ما هو الذكاء بالنسبة لك؟", "Values"),
  createQ("How do you make decisions with little data?", "Comment prends-tu des décisions avec peu de données ?", "كيف تتخذ قرارات ببيانات قليلة؟", "Values"),
  createQ("Do you trust intuition? Why?", "Fais-tu confiance à l'intuition ? Pourquoi ?", "هل تثق في حدسك؟ ولماذا؟", "Values"),
  createQ("What is discipline for you?", "Qu'est-ce que la discipline pour toi ?", "ما هو الانضباط بالنسبة لك؟", "Values"),
  createQ("How do you deal with uncertainty?", "Comment gères-tu l'incertitude ?", "كيف تتعامل مع عدم اليقين؟", "Values"),
  createQ("What is more important: speed or accuracy?", "Qu'est-ce qui est plus important : la vitesse ou la précision ?", "ما هو الأهم: السرعة أم الدقة؟", "Values"),
  createQ("How do you define value?", "Comment définis-tu la valeur ?", "كيف تعرف القيمة؟", "Values"),
  createQ("What is freedom to you?", "Qu'est-ce que la liberté pour toi ?", "ما هي الحرية بالنسبة لك؟", "Values"),
  createQ("How do you face fear?", "Comment affrontes-tu la peur ?", "كيف تواجه الخوف؟", "Values"),
  createQ("What keeps you consistent?", "Qu'est-ce qui te permet de rester constant ?", "ما الذي يجعلك مستمرًا؟", "Values"),
  createQ("How do you react to repeated failure?", "Comment réagis-tu à des échecs répétés ?", "كيف تتصرف مع الفشل المتكرر؟", "Values"),
  createQ("What decision changed your life?", "Quelle décision a changé ta vie ?", "ما القرار الذي غير حياتك؟", "Values"),
  createQ("What does honesty mean to you?", "Que signifie l'honnêteté pour toi ?", "ماذا تعني الأمانة بالنسبة لك؟", "Values"),
  createQ("How do you handle injustice?", "Comment gères-tu l'injustice ?", "كيف تتعامل مع الظلم؟", "Values"),
  createQ("What makes someone respectable?", "Qu'est-ce qui rend quelqu'un respectable ?", "ما الذي يجعل الشخص محترمًا؟", "Values"),
  createQ("How do you balance work and life?", "Comment équilibres-tu travail et vie privée ?", "كيف توازن بين العمل والحياة؟", "Values"),
  createQ("What drains your energy?", "Qu'est-ce qui épuise ton énergie ?", "ما الذي يستنزف طاقتك؟", "Values"),
  createQ("What restores your energy?", "Qu'est-ce qui restaure ton énergie ?", "ما الذي يعيد لك طاقتك؟", "Values"),
  createQ("What does commitment mean to you?", "Que signifie l'engagement pour toi ?", "ماذا يعني الالتزام بالنسبة لك؟", "Values"),
  createQ("How do you learn without being taught?", "Comment apprends-tu sans qu'on t'enseigne ?", "كيف تتعلم دون أن يُعَلّمك أحد؟", "Values"),
  createQ("Difference between knowledge and wisdom?", "Différence entre savoir et sagesse ?", "ما الفرق بين المعرفة والحكمة؟", "Values"),
  createQ("What does time represent to you?", "Que représente le temps pour toi ?", "ماذا يمثل الوقت بالنسبة لك؟", "Values"),
  createQ("How do you handle ambiguity?", "Comment gères-tu l'ambiguïté ?", "كيف تتعامل مع الغموض؟", "Values"),
  createQ("More dangerous: action or inaction?", "Plus dangereux : action ou inaction ?", "أيهما أخطر: الفعل أم عدم الفعل؟", "Values"),
  createQ("How do you define progress?", "Comment définis-tu le progrès ?", "كيف تعرف التقدم؟", "Values"),
  createQ("What do you fear losing most?", "Qu'as-tu le plus peur de perdre ?", "ما أكثر شيء تخشى فقدانه؟", "Values"),
  createQ("What makes you human?", "Qu'est-ce qui te rend humain ?", "ما الذي يجعلك إنسانًا؟", "Values"),
  createQ("How do you face the unknown?", "Comment affrontes-tu l'inconnu ?", "كيف تواجه المجهول؟", "Values"),
  createQ("Hardest truth you accepted?", "La vérité la plus dure que tu as acceptée ?", "ما أصعب حقيقة تقبلتها؟", "Values"),
  createQ("What do you never compromise on?", "Sur quoi ne fais-tu jamais de compromis ?", "ما الذي لا تساوم عليه أبدًا؟", "Values"),
  createQ("How do you earn trust?", "Comment gagnes-tu la confiance ?", "كيف تكسب الثقة؟", "Values"),
  createQ("What does loyalty mean to you?", "Que signifie la loyauté pour toi ?", "ماذا يعني الولاء بالنسبة لك؟", "Values"),
  createQ("What mistake taught you the most?", "Quelle erreur t'a le plus appris ?", "ما الخطأ الذي علمك أكثر؟", "Values"),
  createQ("What makes work meaningful?", "Qu'est-ce qui donne du sens au travail ?", "ما الذي يجعل العمل ذا معنى؟", "Values"),
  createQ("How do you define purpose?", "Comment définis-tu le but ?", "كيف تعرف الغاية؟", "Values"),
  createQ("What is your internal rule?", "Quelle est ta règle interne ?", "ما هي قاعدتك الداخلية؟", "Values"),
  createQ("What does patience mean to you?", "Que signifie la patience pour toi ?", "ماذا يعني الصبر بالنسبة لك؟", "Values"),
  createQ("Relationship with failure?", "Ta relation avec l'échec ?", "ما علاقتك بالفشل؟", "Values"),
  createQ("What makes a good decision?", "Qu'est-ce qui fait une bonne décision ?", "ما الذي يصنع قرارًا جيدًا؟", "Values"),
  createQ("What would you change about yourself?", "Que changerais-tu chez toi ?", "ماذا تغير في نفسك؟", "Values"),
  createQ("Biggest internal conflict?", "Plus grand conflit interne ?", "أكبر صراع داخلي؟", "Values"),
  createQ("How do you control impulses?", "Comment contrôles-tu tes impulsions ?", "كيف تسيطر على اندفاعاتك؟", "Values"),
  createQ("What does respect look like?", "À quoi ressemble le respect ?", "كيف يبدو الاحترام؟", "Values"),
  createQ("What does consistency mean?", "Que signifie la constance ?", "ماذا يعني الاستمرار؟", "Values"),
  createQ("How do you handle boredom?", "Comment gères-tu l'ennui ?", "كيف تتعامل مع الملل؟", "Values"),
  createQ("What motivates long-term effort?", "Qu'est-ce qui motive l'effort à long terme ?", "ما الذي يحفز الجهد طويل الأمد؟", "Values"),
  createQ("Definition of mastery?", "Définition de la maîtrise ?", "ما تعريفك للإتقان؟", "Values"),
  createQ("What does growth feel like?", "À quoi ressemble la croissance ?", "كيف تشعر بالنمو؟", "Values"),
  createQ("What keeps you disciplined?", "Qu'est-ce qui te garde discipliné ?", "ما الذي يبقيك منضبطًا؟", "Values"),
  createQ("What makes you unreliable sometimes?", "Qu'est-ce qui te rend parfois peu fiable ?", "ما الذي يجعلك غير موثوق أحيانًا؟", "Values"),
  createQ("What gives you confidence?", "Qu'est-ce qui te donne confiance ?", "ما الذي يمنحك الثقة؟", "Values"),
  createQ("How do you rebuild after failure?", "Comment te reconstruis-tu après un échec ?", "كيف تعيد بناء نفسك بعد الفشل؟", "Values"),
  createQ("Personal value system?", "Ton système de valeurs personnel ?", "ما هو نظام قيمك الشخصي؟", "Values"),
  createQ("What does success cost?", "Que coûte le succès ?", "ما ثمن النجاح؟", "Values"),
  createQ("Relationship with time pressure?", "Relation avec la pression du temps ?", "علاقتك بضغط الوقت؟", "Values"),
  createQ("What defines a strong mindset?", "Qu'est-ce qui définit un mental fort ?", "ما الذي يعرف العقلية القوية؟", "Values"),
  createQ("What keeps you going when tired?", "Qu'est-ce qui te fait avancer quand tu es fatigué ?", "ما الذي يجعلك تستمر وأنت متعب؟", "Values"),
  createQ("What to improve this year?", "Quoi améliorer cette année ?", "ما الذي يجب تحسينه هذا العام؟", "Values"),
  createQ("Value you bring to the team?", "La valeur que tu apportes à l'équipe ?", "ما القيمة التي تضيفها للفريق؟", "Values"),
  createQ("Why keep you in this team?", "Pourquoi te garder dans cette équipe ?", "لماذا يجب أن نبقيك في الفريق؟", "Values"),

  // PUZZLES (Universal)
  createPuzzle("What increases the more you take from it?"),
  createPuzzle("What has keys but can’t open doors?"),
  createPuzzle("What runs but never walks?"),
  createPuzzle("What comes once in a minute, twice in a moment?"),
  createPuzzle("If you drop me, I’m fine. If you smile, I’m broken. What am I?"),
  createPuzzle("What belongs to you but others use it more?"),
  createPuzzle("What gets wetter the more it dries?"),
  createPuzzle("What has a head and a tail but no body?"),
  createPuzzle("What can travel without moving?"),
  createPuzzle("What has an eye but cannot see?"),
  createPuzzle("Explain time to someone who never experienced it."),
  createPuzzle("Divide a cake into 8 pieces using only 3 cuts."),
  createPuzzle("If all cats are animals and some animals are dogs, are all cats dogs? Explain."),
  createPuzzle("What is silence an answer to?"),
  createPuzzle("What question has no correct answer?"),
  createPuzzle("What is the fastest way to slow time?"),
  createPuzzle("What can you never own but always carry?"),
  createPuzzle("What disappears the moment you say its name?"),
  createPuzzle("If you had no fear, what would change?"),
  createPuzzle("What is heavier: regret or failure? Why?"),
  createPuzzle("Define intelligence without using the word intelligence."),
  createPuzzle("What problem has no solution?"),
  createPuzzle("What is more powerful: truth or belief?"),
  createPuzzle("If time stopped, what would matter?"),
  createPuzzle("What cannot be measured but defines value?"),
  createPuzzle("What is a system without rules?"),
  createPuzzle("What makes a decision wrong?"),
  createPuzzle("Can chaos be controlled? Explain."),
  createPuzzle("What separates humans from machines?"),
  createPuzzle("What does thinking feel like?"),
  createPuzzle("What would you remove from your life to grow?"),
  createPuzzle("What is more dangerous: certainty or doubt?"),
  createPuzzle("What is knowledge without action?"),
  createPuzzle("Can discipline exist without purpose?"),
  createPuzzle("What does focus look like internally?"),
  createPuzzle("What defines mastery?"),
  createPuzzle("What is the cost of comfort?"),
  createPuzzle("What survives when everything fails?"),
  createPuzzle("What should be questioned more?"),
  createPuzzle("What is the most important question to ask yourself?")
];